FROM node

# Create work directory
RUN mkdir /app
WORKDIR /app

# Install dependencies
ADD ./package.json /app
RUN npm install

# Add all the additional source code
COPY . /app/

CMD ["npm", "run", "build", "--production"]
